spring.application.name=airline-dcs

spring.datasource.url=jdbc:postgresql://localhost:5432/airlinedcs
spring.datasource.username=postgres
spring.datasource.password=Postgresql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
